=begin
#User API

#The User API represents all functionality that a user in Design Huddle may perform. Every API method is run in the context of a single user and requires a user-specific Access Token for authorization. The most common integration use cases consist of listing templates, creating design projects from those templates and exporting the finished designs. Read more about authentication <a target=\"_parent\" href=\"https://api.designhuddle.com#authentication\">here</a> and embedding the Design Huddle editor <a target=\"_parent\" href=\"https://api.designhuddle.com#embedding\">here</a>.

The version of the OpenAPI document: 2023-02-02T22:11:12Z
Contact: support@designhuddle.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DesignHuddleUser::ExportApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ExportApi' do
  before do
    # run before each test
    @api_instance = DesignHuddleUser::ExportApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExportApi' do
    it 'should create an instance of ExportApi' do
      expect(@api_instance).to be_instance_of(DesignHuddleUser::ExportApi)
    end
  end

  # unit tests for projects_project_id_export_jobs_job_id_get
  # Retrieve export job progress
  # @param job_id 
  # @param project_id 
  # @param [Hash] opts the optional parameters
  # @return [ProjectsProjectIDExportJobsJobIDGETSuccess]
  describe 'projects_project_id_export_jobs_job_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for projects_project_id_export_post
  # Create an export job
  # @param project_id 
  # @param projects_project_id_export_post_request 
  # @param [Hash] opts the optional parameters
  # @return [ProjectsProjectIDExportPOSTSuccess]
  describe 'projects_project_id_export_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
