=begin
#User API

#The User API represents all functionality that a user in Design Huddle may perform. Every API method is run in the context of a single user and requires a user-specific Access Token for authorization. The most common integration use cases consist of listing templates, creating design projects from those templates and exporting the finished designs. Read more about authentication <a target=\"_parent\" href=\"https://api.designhuddle.com#authentication\">here</a> and embedding the Design Huddle editor <a target=\"_parent\" href=\"https://api.designhuddle.com#embedding\">here</a>.

The version of the OpenAPI document: 2023-02-02T22:11:12Z
Contact: support@designhuddle.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

require 'spec_helper'
require 'json'

# Unit tests for DesignHuddleUser::TemplatesApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TemplatesApi' do
  before do
    # run before each test
    @api_instance = DesignHuddleUser::TemplatesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TemplatesApi' do
    it 'should create an instance of TemplatesApi' do
      expect(@api_instance).to be_instance_of(DesignHuddleUser::TemplatesApi)
    end
  end

  # unit tests for gallery_templates_get
  # List templates
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :template_id Specify the Template ID to filter the result by.
  # @option opts [Array<Integer>] :template_ids Specify the Template IDs to filter the result by.
  # @option opts [String] :template_code Specify the Template Code to filter the result by.
  # @option opts [Array<String>] :template_codes Specify the Template Codes to filter the result by.
  # @option opts [Integer] :brand_id Specify the Brand ID to filter the result by.
  # @option opts [String] :brand_code Specify the Brand Code to filter the result by.
  # @option opts [String] :media_type Specify the media type to filter the result by.
  # @option opts [Array<String>] :media_types Specify the media types to filter the result by.
  # @option opts [Integer] :primary_template_category_item_id Specify the Primary Template Category Item ID to filter the result by.
  # @option opts [Array<Integer>] :primary_template_category_item_ids Specify the Primary Template Category Item IDs to filter the result by.
  # @option opts [Integer] :width Specify the width to filter the result by.
  # @option opts [Integer] :height Specify the height to filter the result by.
  # @option opts [String] :unit_type Specify the unit type to filter the result by.
  # @option opts [String] :search A search term used to narrow the focus of the result.
  # @option opts [String] :sort Specify which attribute to order the result by.
  # @option opts [String] :order Specify whether the result should be retrieved in ascending or descending order.
  # @option opts [Integer] :limit Specify the number of items per page to return.
  # @option opts [Integer] :page Specify which page of the result to return.
  # @option opts [Array<String>] :fields Specify the fields to the retrieve.
  # @return [GalleryTemplatesGETSuccess]
  describe 'gallery_templates_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for template_customization_objects_post
  # Create a template customization object
  # @param template_customization_objects_post_request 
  # @param [Hash] opts the optional parameters
  # @return [TemplateCustomizationObjectsPOSTSuccess]
  describe 'template_customization_objects_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
