=begin
#User API

#The User API represents all functionality that a user in Design Huddle may perform. Every API method is run in the context of a single user and requires a user-specific Access Token for authorization. The most common integration use cases consist of listing templates, creating design projects from those templates and exporting the finished designs. Read more about authentication <a target=\"_parent\" href=\"https://api.designhuddle.com#authentication\">here</a> and embedding the Design Huddle editor <a target=\"_parent\" href=\"https://api.designhuddle.com#embedding\">here</a>.

The version of the OpenAPI document: 2023-02-02T22:11:12Z
Contact: support@designhuddle.com
Generated by: https://openapi-generator.tech
OpenAPI Generator version: 6.3.0

=end

# Common files
require 'design_huddle_user/api_client'
require 'design_huddle_user/api_error'
require 'design_huddle_user/version'
require 'design_huddle_user/configuration'

# Models
require 'design_huddle_user/models/base_create_success'
require 'design_huddle_user/models/base_error'
require 'design_huddle_user/models/base_success'
require 'design_huddle_user/models/brand'
require 'design_huddle_user/models/dimensions'
require 'design_huddle_user/models/gallery_templates_get_success'
require 'design_huddle_user/models/list_success'
require 'design_huddle_user/models/media_type'
require 'design_huddle_user/models/page'
require 'design_huddle_user/models/page_scene_slides_inner'
require 'design_huddle_user/models/project_approval_log'
require 'design_huddle_user/models/project_approval_status'
require 'design_huddle_user/models/project_status'
require 'design_huddle_user/models/projects_get_success'
require 'design_huddle_user/models/projects_post_request'
require 'design_huddle_user/models/projects_post_request_one_of'
require 'design_huddle_user/models/projects_post_request_one_of1'
require 'design_huddle_user/models/projects_post_request_one_of2'
require 'design_huddle_user/models/projects_post_request_one_of2_dimensions'
require 'design_huddle_user/models/projects_post_request_one_of3'
require 'design_huddle_user/models/projects_post_request_one_of4'
require 'design_huddle_user/models/projects_post_request_one_of5'
require 'design_huddle_user/models/projects_post_request_one_of6'
require 'design_huddle_user/models/projects_post_request_one_of6_dimensions'
require 'design_huddle_user/models/projects_post_success'
require 'design_huddle_user/models/projects_project_id_error403'
require 'design_huddle_user/models/projects_project_id_error404'
require 'design_huddle_user/models/projects_project_id_export_jobs_job_id_error403'
require 'design_huddle_user/models/projects_project_id_export_jobs_job_idget_success'
require 'design_huddle_user/models/projects_project_id_export_jobs_job_idget_success_one_of'
require 'design_huddle_user/models/projects_project_id_export_jobs_job_idget_success_one_of1'
require 'design_huddle_user/models/projects_project_id_export_jobs_job_idget_success_one_of1_data'
require 'design_huddle_user/models/projects_project_id_export_jobs_job_idget_success_one_of_data'
require 'design_huddle_user/models/projects_project_id_export_post_request'
require 'design_huddle_user/models/projects_project_id_export_post_request_one_of'
require 'design_huddle_user/models/projects_project_id_export_post_request_one_of1'
require 'design_huddle_user/models/projects_project_id_export_post_request_one_of1_bleed'
require 'design_huddle_user/models/projects_project_id_export_post_request_one_of1_bleed_margin'
require 'design_huddle_user/models/projects_project_id_export_post_request_one_of2'
require 'design_huddle_user/models/projects_project_id_export_post_request_one_of3'
require 'design_huddle_user/models/projects_project_id_export_post_request_one_of4'
require 'design_huddle_user/models/projects_project_id_export_post_success'
require 'design_huddle_user/models/projects_project_idget_success'
require 'design_huddle_user/models/projects_project_idpatch_request'
require 'design_huddle_user/models/scene'
require 'design_huddle_user/models/scene_scene_slides_inner'
require 'design_huddle_user/models/template_customization_objects_post_request'
require 'design_huddle_user/models/template_customization_objects_post_success'
require 'design_huddle_user/models/unit_type'

# APIs
require 'design_huddle_user/api/export_api'
require 'design_huddle_user/api/projects_api'
require 'design_huddle_user/api/templates_api'

module DesignHuddleUser
  class << self
    # Customize default settings for the SDK using block.
    #   DesignHuddleUser.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
